{"name": "Тест получения заказа с несуществующим номером", "status": "passed", "description": "Запрос с несуществующим заказом возвращает ошибку Not Found", "steps": [{"name": "Отправляем запрос на получение заказа по его номеру", "status": "passed", "parameters": [{"name": "t", "value": "6813589"}], "start": 1715023443957, "stop": 1715023444628}], "start": 1715023443956, "stop": 1715023444630, "uuid": "0103f280-0096-47be-90d6-35a9b2b9bf03", "historyId": "7f3a997c81a64394e911485ed5d5ecb9", "testCaseId": "7f3a997c81a64394e911485ed5d5ecb9", "fullName": "tests.test_orders_track.TestOrdersTrack#test_track_order_wrong_id_return_not_found_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_orders_track"}, {"name": "subSuite", "value": "TestOrdersTrack"}, {"name": "host", "value": "DESKTOP-9PI1IG9"}, {"name": "thread", "value": "9108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orders_track"}]}